apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: graphql-newdev
deploy:
  helm:
    releases:
    - name: graphql-newdev
      chartPath: charts
      namespace: dev
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image.address: graphql-newdev
      #recreatePods will pass --recreate-pods to helm upgrade
    #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue