import { PlatformEventMenuPage, PlatformEventMenuSettings } from "../inputs/event";

export const PAGE_MAPPING: { [key: string]: PlatformEventMenuSettings[] } = {
  REGULAR: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'content', type: PlatformEventMenuPage.CONTENT },
    { label: 'companies', type: PlatformEventMenuPage.COMPANIES },
    { label: 'attendees', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  TRADE: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'agenda', type: PlatformEventMenuPage.CONTENT },
    { label: 'companies', type: PlatformEventMenuPage.COMPANIES },
    { label: 'attendees', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  RESTAURANT: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'services', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  SALON: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'services', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  MEETINGROOMS: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'content', type: PlatformEventMenuPage.CONTENT },
    { label: 'companies', type: PlatformEventMenuPage.COMPANIES },
    { label: 'attendees', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  GATHERING: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'guests', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  EXHIBITION: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'companies', type: PlatformEventMenuPage.COMPANIES },
    { label: 'attendees', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  BIRTHDAY: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'guest', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  MECHANIC: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'services', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING }
  ],
  PHOTOGRAPHY: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'services', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  CINEMA: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'movies', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  MUSEUM: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  CONFERENCES: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'companies', type: PlatformEventMenuPage.COMPANIES },
    { label: 'attendees', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  WEDDINGS: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'guests', type: PlatformEventMenuPage.ATTENDEES },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  TENNIS: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  BASKETBALL: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  FOOTBALL: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  SQUASH: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  GARAGE: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  RUGBY: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  AFL: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  SPORT: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  NFL: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'members', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  SURGERY: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
  DENTIST: [
    { label: 'home', type: PlatformEventMenuPage.HOME },
    { label: 'calendar', type: PlatformEventMenuPage.CALENDAR },
    { label: 'info', type: PlatformEventMenuPage.CONTENT },
    { label: 'suppliers', type: PlatformEventMenuPage.COMPANIES, adminOnly: true },
    { label: 'clients', type: PlatformEventMenuPage.ATTENDEES, adminOnly: true },
    { label: 'pricing', type: PlatformEventMenuPage.CONTENT_PRICING },
    { label: 'cluster', type: PlatformEventMenuPage.CLUSTER },
  ],
}
